// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

package protblog;

public final class PlayerOuterClass {
  private PlayerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protblog.Class}
   */
  public enum Class
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Berserk = 0;</code>
     */
    Berserk(0),
    /**
     * <code>Tank = 1;</code>
     */
    Tank(1),
    /**
     * <code>Paladin = 3;</code>
     */
    Paladin(3),
    /**
     * <code>Mage = 4;</code>
     */
    Mage(4),
    ;

    /**
     * <code>Berserk = 0;</code>
     */
    public static final int Berserk_VALUE = 0;
    /**
     * <code>Tank = 1;</code>
     */
    public static final int Tank_VALUE = 1;
    /**
     * <code>Paladin = 3;</code>
     */
    public static final int Paladin_VALUE = 3;
    /**
     * <code>Mage = 4;</code>
     */
    public static final int Mage_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Class valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Class forNumber(int value) {
      switch (value) {
        case 0: return Berserk;
        case 1: return Tank;
        case 3: return Paladin;
        case 4: return Mage;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Class>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Class> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Class>() {
            public Class findValueByNumber(int number) {
              return Class.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protblog.PlayerOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Class[] VALUES = values();

    public static Class valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Class(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protblog.Class)
  }

  public interface PlayersListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protblog.PlayersList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protblog.PlayersList.Player player = 1;</code>
     */
    java.util.List<protblog.PlayerOuterClass.PlayersList.Player> 
        getPlayerList();
    /**
     * <code>repeated .protblog.PlayersList.Player player = 1;</code>
     */
    protblog.PlayerOuterClass.PlayersList.Player getPlayer(int index);
    /**
     * <code>repeated .protblog.PlayersList.Player player = 1;</code>
     */
    int getPlayerCount();
    /**
     * <code>repeated .protblog.PlayersList.Player player = 1;</code>
     */
    java.util.List<? extends protblog.PlayerOuterClass.PlayersList.PlayerOrBuilder> 
        getPlayerOrBuilderList();
    /**
     * <code>repeated .protblog.PlayersList.Player player = 1;</code>
     */
    protblog.PlayerOuterClass.PlayersList.PlayerOrBuilder getPlayerOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protblog.PlayersList}
   */
  public static final class PlayersList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protblog.PlayersList)
      PlayersListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayersList.newBuilder() to construct.
    private PlayersList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayersList() {
      player_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayersList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protblog.PlayerOuterClass.internal_static_protblog_PlayersList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protblog.PlayerOuterClass.internal_static_protblog_PlayersList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protblog.PlayerOuterClass.PlayersList.class, protblog.PlayerOuterClass.PlayersList.Builder.class);
    }

    public interface PlayerOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protblog.PlayersList.Player)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string nickname = 1;</code>
       * @return Whether the nickname field is set.
       */
      boolean hasNickname();
      /**
       * <code>required string nickname = 1;</code>
       * @return The nickname.
       */
      java.lang.String getNickname();
      /**
       * <code>required string nickname = 1;</code>
       * @return The bytes for nickname.
       */
      com.google.protobuf.ByteString
          getNicknameBytes();

      /**
       * <code>required string email = 2;</code>
       * @return Whether the email field is set.
       */
      boolean hasEmail();
      /**
       * <code>required string email = 2;</code>
       * @return The email.
       */
      java.lang.String getEmail();
      /**
       * <code>required string email = 2;</code>
       * @return The bytes for email.
       */
      com.google.protobuf.ByteString
          getEmailBytes();

      /**
       * <code>required string date_of_birth = 3;</code>
       * @return Whether the dateOfBirth field is set.
       */
      boolean hasDateOfBirth();
      /**
       * <code>required string date_of_birth = 3;</code>
       * @return The dateOfBirth.
       */
      java.lang.String getDateOfBirth();
      /**
       * <code>required string date_of_birth = 3;</code>
       * @return The bytes for dateOfBirth.
       */
      com.google.protobuf.ByteString
          getDateOfBirthBytes();

      /**
       * <code>required int32 xp = 4;</code>
       * @return Whether the xp field is set.
       */
      boolean hasXp();
      /**
       * <code>required int32 xp = 4;</code>
       * @return The xp.
       */
      int getXp();

      /**
       * <code>required .protblog.Class cls = 5;</code>
       * @return Whether the cls field is set.
       */
      boolean hasCls();
      /**
       * <code>required .protblog.Class cls = 5;</code>
       * @return The cls.
       */
      protblog.PlayerOuterClass.Class getCls();
    }
    /**
     * Protobuf type {@code protblog.PlayersList.Player}
     */
    public static final class Player extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:protblog.PlayersList.Player)
        PlayerOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Player.newBuilder() to construct.
      private Player(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Player() {
        nickname_ = "";
        email_ = "";
        dateOfBirth_ = "";
        cls_ = 0;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Player();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protblog.PlayerOuterClass.internal_static_protblog_PlayersList_Player_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protblog.PlayerOuterClass.internal_static_protblog_PlayersList_Player_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protblog.PlayerOuterClass.PlayersList.Player.class, protblog.PlayerOuterClass.PlayersList.Player.Builder.class);
      }

      private int bitField0_;
      public static final int NICKNAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object nickname_;
      /**
       * <code>required string nickname = 1;</code>
       * @return Whether the nickname field is set.
       */
      @java.lang.Override
      public boolean hasNickname() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string nickname = 1;</code>
       * @return The nickname.
       */
      @java.lang.Override
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickname_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string nickname = 1;</code>
       * @return The bytes for nickname.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int EMAIL_FIELD_NUMBER = 2;
      private volatile java.lang.Object email_;
      /**
       * <code>required string email = 2;</code>
       * @return Whether the email field is set.
       */
      @java.lang.Override
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string email = 2;</code>
       * @return The email.
       */
      @java.lang.Override
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string email = 2;</code>
       * @return The bytes for email.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DATE_OF_BIRTH_FIELD_NUMBER = 3;
      private volatile java.lang.Object dateOfBirth_;
      /**
       * <code>required string date_of_birth = 3;</code>
       * @return Whether the dateOfBirth field is set.
       */
      @java.lang.Override
      public boolean hasDateOfBirth() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string date_of_birth = 3;</code>
       * @return The dateOfBirth.
       */
      @java.lang.Override
      public java.lang.String getDateOfBirth() {
        java.lang.Object ref = dateOfBirth_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dateOfBirth_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string date_of_birth = 3;</code>
       * @return The bytes for dateOfBirth.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDateOfBirthBytes() {
        java.lang.Object ref = dateOfBirth_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateOfBirth_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int XP_FIELD_NUMBER = 4;
      private int xp_;
      /**
       * <code>required int32 xp = 4;</code>
       * @return Whether the xp field is set.
       */
      @java.lang.Override
      public boolean hasXp() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int32 xp = 4;</code>
       * @return The xp.
       */
      @java.lang.Override
      public int getXp() {
        return xp_;
      }

      public static final int CLS_FIELD_NUMBER = 5;
      private int cls_;
      /**
       * <code>required .protblog.Class cls = 5;</code>
       * @return Whether the cls field is set.
       */
      @java.lang.Override public boolean hasCls() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required .protblog.Class cls = 5;</code>
       * @return The cls.
       */
      @java.lang.Override public protblog.PlayerOuterClass.Class getCls() {
        @SuppressWarnings("deprecation")
        protblog.PlayerOuterClass.Class result = protblog.PlayerOuterClass.Class.valueOf(cls_);
        return result == null ? protblog.PlayerOuterClass.Class.Berserk : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasNickname()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasEmail()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDateOfBirth()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasXp()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasCls()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nickname_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, email_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dateOfBirth_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          output.writeInt32(4, xp_);
        }
        if (((bitField0_ & 0x00000010) != 0)) {
          output.writeEnum(5, cls_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nickname_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, email_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dateOfBirth_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, xp_);
        }
        if (((bitField0_ & 0x00000010) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(5, cls_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof protblog.PlayerOuterClass.PlayersList.Player)) {
          return super.equals(obj);
        }
        protblog.PlayerOuterClass.PlayersList.Player other = (protblog.PlayerOuterClass.PlayersList.Player) obj;

        if (hasNickname() != other.hasNickname()) return false;
        if (hasNickname()) {
          if (!getNickname()
              .equals(other.getNickname())) return false;
        }
        if (hasEmail() != other.hasEmail()) return false;
        if (hasEmail()) {
          if (!getEmail()
              .equals(other.getEmail())) return false;
        }
        if (hasDateOfBirth() != other.hasDateOfBirth()) return false;
        if (hasDateOfBirth()) {
          if (!getDateOfBirth()
              .equals(other.getDateOfBirth())) return false;
        }
        if (hasXp() != other.hasXp()) return false;
        if (hasXp()) {
          if (getXp()
              != other.getXp()) return false;
        }
        if (hasCls() != other.hasCls()) return false;
        if (hasCls()) {
          if (cls_ != other.cls_) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasNickname()) {
          hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
          hash = (53 * hash) + getNickname().hashCode();
        }
        if (hasEmail()) {
          hash = (37 * hash) + EMAIL_FIELD_NUMBER;
          hash = (53 * hash) + getEmail().hashCode();
        }
        if (hasDateOfBirth()) {
          hash = (37 * hash) + DATE_OF_BIRTH_FIELD_NUMBER;
          hash = (53 * hash) + getDateOfBirth().hashCode();
        }
        if (hasXp()) {
          hash = (37 * hash) + XP_FIELD_NUMBER;
          hash = (53 * hash) + getXp();
        }
        if (hasCls()) {
          hash = (37 * hash) + CLS_FIELD_NUMBER;
          hash = (53 * hash) + cls_;
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static protblog.PlayerOuterClass.PlayersList.Player parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protblog.PlayerOuterClass.PlayersList.Player parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protblog.PlayerOuterClass.PlayersList.Player parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protblog.PlayerOuterClass.PlayersList.Player parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protblog.PlayerOuterClass.PlayersList.Player parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protblog.PlayerOuterClass.PlayersList.Player parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protblog.PlayerOuterClass.PlayersList.Player parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static protblog.PlayerOuterClass.PlayersList.Player parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static protblog.PlayerOuterClass.PlayersList.Player parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static protblog.PlayerOuterClass.PlayersList.Player parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static protblog.PlayerOuterClass.PlayersList.Player parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static protblog.PlayerOuterClass.PlayersList.Player parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(protblog.PlayerOuterClass.PlayersList.Player prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protblog.PlayersList.Player}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protblog.PlayersList.Player)
          protblog.PlayerOuterClass.PlayersList.PlayerOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return protblog.PlayerOuterClass.internal_static_protblog_PlayersList_Player_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return protblog.PlayerOuterClass.internal_static_protblog_PlayersList_Player_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  protblog.PlayerOuterClass.PlayersList.Player.class, protblog.PlayerOuterClass.PlayersList.Player.Builder.class);
        }

        // Construct using protblog.PlayerOuterClass.PlayersList.Player.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          nickname_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          email_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          dateOfBirth_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          xp_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          cls_ = 0;
          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return protblog.PlayerOuterClass.internal_static_protblog_PlayersList_Player_descriptor;
        }

        @java.lang.Override
        public protblog.PlayerOuterClass.PlayersList.Player getDefaultInstanceForType() {
          return protblog.PlayerOuterClass.PlayersList.Player.getDefaultInstance();
        }

        @java.lang.Override
        public protblog.PlayerOuterClass.PlayersList.Player build() {
          protblog.PlayerOuterClass.PlayersList.Player result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public protblog.PlayerOuterClass.PlayersList.Player buildPartial() {
          protblog.PlayerOuterClass.PlayersList.Player result = new protblog.PlayerOuterClass.PlayersList.Player(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.nickname_ = nickname_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            to_bitField0_ |= 0x00000002;
          }
          result.email_ = email_;
          if (((from_bitField0_ & 0x00000004) != 0)) {
            to_bitField0_ |= 0x00000004;
          }
          result.dateOfBirth_ = dateOfBirth_;
          if (((from_bitField0_ & 0x00000008) != 0)) {
            result.xp_ = xp_;
            to_bitField0_ |= 0x00000008;
          }
          if (((from_bitField0_ & 0x00000010) != 0)) {
            to_bitField0_ |= 0x00000010;
          }
          result.cls_ = cls_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof protblog.PlayerOuterClass.PlayersList.Player) {
            return mergeFrom((protblog.PlayerOuterClass.PlayersList.Player)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(protblog.PlayerOuterClass.PlayersList.Player other) {
          if (other == protblog.PlayerOuterClass.PlayersList.Player.getDefaultInstance()) return this;
          if (other.hasNickname()) {
            bitField0_ |= 0x00000001;
            nickname_ = other.nickname_;
            onChanged();
          }
          if (other.hasEmail()) {
            bitField0_ |= 0x00000002;
            email_ = other.email_;
            onChanged();
          }
          if (other.hasDateOfBirth()) {
            bitField0_ |= 0x00000004;
            dateOfBirth_ = other.dateOfBirth_;
            onChanged();
          }
          if (other.hasXp()) {
            setXp(other.getXp());
          }
          if (other.hasCls()) {
            setCls(other.getCls());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasNickname()) {
            return false;
          }
          if (!hasEmail()) {
            return false;
          }
          if (!hasDateOfBirth()) {
            return false;
          }
          if (!hasXp()) {
            return false;
          }
          if (!hasCls()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  nickname_ = input.readBytes();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 18: {
                  email_ = input.readBytes();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                case 26: {
                  dateOfBirth_ = input.readBytes();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 26
                case 32: {
                  xp_ = input.readInt32();
                  bitField0_ |= 0x00000008;
                  break;
                } // case 32
                case 40: {
                  int tmpRaw = input.readEnum();
                  protblog.PlayerOuterClass.Class tmpValue =
                      protblog.PlayerOuterClass.Class.forNumber(tmpRaw);
                  if (tmpValue == null) {
                    mergeUnknownVarintField(5, tmpRaw);
                  } else {
                    cls_ = tmpRaw;
                    bitField0_ |= 0x00000010;
                  }
                  break;
                } // case 40
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object nickname_ = "";
        /**
         * <code>required string nickname = 1;</code>
         * @return Whether the nickname field is set.
         */
        public boolean hasNickname() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required string nickname = 1;</code>
         * @return The nickname.
         */
        public java.lang.String getNickname() {
          java.lang.Object ref = nickname_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              nickname_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string nickname = 1;</code>
         * @return The bytes for nickname.
         */
        public com.google.protobuf.ByteString
            getNicknameBytes() {
          java.lang.Object ref = nickname_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            nickname_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string nickname = 1;</code>
         * @param value The nickname to set.
         * @return This builder for chaining.
         */
        public Builder setNickname(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          nickname_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string nickname = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearNickname() {
          bitField0_ = (bitField0_ & ~0x00000001);
          nickname_ = getDefaultInstance().getNickname();
          onChanged();
          return this;
        }
        /**
         * <code>required string nickname = 1;</code>
         * @param value The bytes for nickname to set.
         * @return This builder for chaining.
         */
        public Builder setNicknameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          nickname_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object email_ = "";
        /**
         * <code>required string email = 2;</code>
         * @return Whether the email field is set.
         */
        public boolean hasEmail() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required string email = 2;</code>
         * @return The email.
         */
        public java.lang.String getEmail() {
          java.lang.Object ref = email_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              email_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string email = 2;</code>
         * @return The bytes for email.
         */
        public com.google.protobuf.ByteString
            getEmailBytes() {
          java.lang.Object ref = email_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            email_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string email = 2;</code>
         * @param value The email to set.
         * @return This builder for chaining.
         */
        public Builder setEmail(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          email_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string email = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearEmail() {
          bitField0_ = (bitField0_ & ~0x00000002);
          email_ = getDefaultInstance().getEmail();
          onChanged();
          return this;
        }
        /**
         * <code>required string email = 2;</code>
         * @param value The bytes for email to set.
         * @return This builder for chaining.
         */
        public Builder setEmailBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          email_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object dateOfBirth_ = "";
        /**
         * <code>required string date_of_birth = 3;</code>
         * @return Whether the dateOfBirth field is set.
         */
        public boolean hasDateOfBirth() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>required string date_of_birth = 3;</code>
         * @return The dateOfBirth.
         */
        public java.lang.String getDateOfBirth() {
          java.lang.Object ref = dateOfBirth_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              dateOfBirth_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string date_of_birth = 3;</code>
         * @return The bytes for dateOfBirth.
         */
        public com.google.protobuf.ByteString
            getDateOfBirthBytes() {
          java.lang.Object ref = dateOfBirth_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            dateOfBirth_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string date_of_birth = 3;</code>
         * @param value The dateOfBirth to set.
         * @return This builder for chaining.
         */
        public Builder setDateOfBirth(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          dateOfBirth_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string date_of_birth = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearDateOfBirth() {
          bitField0_ = (bitField0_ & ~0x00000004);
          dateOfBirth_ = getDefaultInstance().getDateOfBirth();
          onChanged();
          return this;
        }
        /**
         * <code>required string date_of_birth = 3;</code>
         * @param value The bytes for dateOfBirth to set.
         * @return This builder for chaining.
         */
        public Builder setDateOfBirthBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          dateOfBirth_ = value;
          onChanged();
          return this;
        }

        private int xp_ ;
        /**
         * <code>required int32 xp = 4;</code>
         * @return Whether the xp field is set.
         */
        @java.lang.Override
        public boolean hasXp() {
          return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <code>required int32 xp = 4;</code>
         * @return The xp.
         */
        @java.lang.Override
        public int getXp() {
          return xp_;
        }
        /**
         * <code>required int32 xp = 4;</code>
         * @param value The xp to set.
         * @return This builder for chaining.
         */
        public Builder setXp(int value) {
          bitField0_ |= 0x00000008;
          xp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 xp = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearXp() {
          bitField0_ = (bitField0_ & ~0x00000008);
          xp_ = 0;
          onChanged();
          return this;
        }

        private int cls_ = 0;
        /**
         * <code>required .protblog.Class cls = 5;</code>
         * @return Whether the cls field is set.
         */
        @java.lang.Override public boolean hasCls() {
          return ((bitField0_ & 0x00000010) != 0);
        }
        /**
         * <code>required .protblog.Class cls = 5;</code>
         * @return The cls.
         */
        @java.lang.Override
        public protblog.PlayerOuterClass.Class getCls() {
          @SuppressWarnings("deprecation")
          protblog.PlayerOuterClass.Class result = protblog.PlayerOuterClass.Class.valueOf(cls_);
          return result == null ? protblog.PlayerOuterClass.Class.Berserk : result;
        }
        /**
         * <code>required .protblog.Class cls = 5;</code>
         * @param value The cls to set.
         * @return This builder for chaining.
         */
        public Builder setCls(protblog.PlayerOuterClass.Class value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000010;
          cls_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required .protblog.Class cls = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearCls() {
          bitField0_ = (bitField0_ & ~0x00000010);
          cls_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:protblog.PlayersList.Player)
      }

      // @@protoc_insertion_point(class_scope:protblog.PlayersList.Player)
      private static final protblog.PlayerOuterClass.PlayersList.Player DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new protblog.PlayerOuterClass.PlayersList.Player();
      }

      public static protblog.PlayerOuterClass.PlayersList.Player getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Player>
          PARSER = new com.google.protobuf.AbstractParser<Player>() {
        @java.lang.Override
        public Player parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Player> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Player> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public protblog.PlayerOuterClass.PlayersList.Player getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PLAYER_FIELD_NUMBER = 1;
    private java.util.List<protblog.PlayerOuterClass.PlayersList.Player> player_;
    /**
     * <code>repeated .protblog.PlayersList.Player player = 1;</code>
     */
    @java.lang.Override
    public java.util.List<protblog.PlayerOuterClass.PlayersList.Player> getPlayerList() {
      return player_;
    }
    /**
     * <code>repeated .protblog.PlayersList.Player player = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends protblog.PlayerOuterClass.PlayersList.PlayerOrBuilder> 
        getPlayerOrBuilderList() {
      return player_;
    }
    /**
     * <code>repeated .protblog.PlayersList.Player player = 1;</code>
     */
    @java.lang.Override
    public int getPlayerCount() {
      return player_.size();
    }
    /**
     * <code>repeated .protblog.PlayersList.Player player = 1;</code>
     */
    @java.lang.Override
    public protblog.PlayerOuterClass.PlayersList.Player getPlayer(int index) {
      return player_.get(index);
    }
    /**
     * <code>repeated .protblog.PlayersList.Player player = 1;</code>
     */
    @java.lang.Override
    public protblog.PlayerOuterClass.PlayersList.PlayerOrBuilder getPlayerOrBuilder(
        int index) {
      return player_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPlayerCount(); i++) {
        if (!getPlayer(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < player_.size(); i++) {
        output.writeMessage(1, player_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < player_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, player_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protblog.PlayerOuterClass.PlayersList)) {
        return super.equals(obj);
      }
      protblog.PlayerOuterClass.PlayersList other = (protblog.PlayerOuterClass.PlayersList) obj;

      if (!getPlayerList()
          .equals(other.getPlayerList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPlayerCount() > 0) {
        hash = (37 * hash) + PLAYER_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protblog.PlayerOuterClass.PlayersList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protblog.PlayerOuterClass.PlayersList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protblog.PlayerOuterClass.PlayersList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protblog.PlayerOuterClass.PlayersList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protblog.PlayerOuterClass.PlayersList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protblog.PlayerOuterClass.PlayersList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protblog.PlayerOuterClass.PlayersList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protblog.PlayerOuterClass.PlayersList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protblog.PlayerOuterClass.PlayersList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protblog.PlayerOuterClass.PlayersList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protblog.PlayerOuterClass.PlayersList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protblog.PlayerOuterClass.PlayersList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protblog.PlayerOuterClass.PlayersList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protblog.PlayersList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protblog.PlayersList)
        protblog.PlayerOuterClass.PlayersListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protblog.PlayerOuterClass.internal_static_protblog_PlayersList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protblog.PlayerOuterClass.internal_static_protblog_PlayersList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protblog.PlayerOuterClass.PlayersList.class, protblog.PlayerOuterClass.PlayersList.Builder.class);
      }

      // Construct using protblog.PlayerOuterClass.PlayersList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (playerBuilder_ == null) {
          player_ = java.util.Collections.emptyList();
        } else {
          player_ = null;
          playerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protblog.PlayerOuterClass.internal_static_protblog_PlayersList_descriptor;
      }

      @java.lang.Override
      public protblog.PlayerOuterClass.PlayersList getDefaultInstanceForType() {
        return protblog.PlayerOuterClass.PlayersList.getDefaultInstance();
      }

      @java.lang.Override
      public protblog.PlayerOuterClass.PlayersList build() {
        protblog.PlayerOuterClass.PlayersList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protblog.PlayerOuterClass.PlayersList buildPartial() {
        protblog.PlayerOuterClass.PlayersList result = new protblog.PlayerOuterClass.PlayersList(this);
        int from_bitField0_ = bitField0_;
        if (playerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            player_ = java.util.Collections.unmodifiableList(player_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.player_ = player_;
        } else {
          result.player_ = playerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protblog.PlayerOuterClass.PlayersList) {
          return mergeFrom((protblog.PlayerOuterClass.PlayersList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protblog.PlayerOuterClass.PlayersList other) {
        if (other == protblog.PlayerOuterClass.PlayersList.getDefaultInstance()) return this;
        if (playerBuilder_ == null) {
          if (!other.player_.isEmpty()) {
            if (player_.isEmpty()) {
              player_ = other.player_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePlayerIsMutable();
              player_.addAll(other.player_);
            }
            onChanged();
          }
        } else {
          if (!other.player_.isEmpty()) {
            if (playerBuilder_.isEmpty()) {
              playerBuilder_.dispose();
              playerBuilder_ = null;
              player_ = other.player_;
              bitField0_ = (bitField0_ & ~0x00000001);
              playerBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPlayerFieldBuilder() : null;
            } else {
              playerBuilder_.addAllMessages(other.player_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getPlayerCount(); i++) {
          if (!getPlayer(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                protblog.PlayerOuterClass.PlayersList.Player m =
                    input.readMessage(
                        protblog.PlayerOuterClass.PlayersList.Player.PARSER,
                        extensionRegistry);
                if (playerBuilder_ == null) {
                  ensurePlayerIsMutable();
                  player_.add(m);
                } else {
                  playerBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<protblog.PlayerOuterClass.PlayersList.Player> player_ =
        java.util.Collections.emptyList();
      private void ensurePlayerIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          player_ = new java.util.ArrayList<protblog.PlayerOuterClass.PlayersList.Player>(player_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protblog.PlayerOuterClass.PlayersList.Player, protblog.PlayerOuterClass.PlayersList.Player.Builder, protblog.PlayerOuterClass.PlayersList.PlayerOrBuilder> playerBuilder_;

      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public java.util.List<protblog.PlayerOuterClass.PlayersList.Player> getPlayerList() {
        if (playerBuilder_ == null) {
          return java.util.Collections.unmodifiableList(player_);
        } else {
          return playerBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public int getPlayerCount() {
        if (playerBuilder_ == null) {
          return player_.size();
        } else {
          return playerBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public protblog.PlayerOuterClass.PlayersList.Player getPlayer(int index) {
        if (playerBuilder_ == null) {
          return player_.get(index);
        } else {
          return playerBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public Builder setPlayer(
          int index, protblog.PlayerOuterClass.PlayersList.Player value) {
        if (playerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerIsMutable();
          player_.set(index, value);
          onChanged();
        } else {
          playerBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public Builder setPlayer(
          int index, protblog.PlayerOuterClass.PlayersList.Player.Builder builderForValue) {
        if (playerBuilder_ == null) {
          ensurePlayerIsMutable();
          player_.set(index, builderForValue.build());
          onChanged();
        } else {
          playerBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public Builder addPlayer(protblog.PlayerOuterClass.PlayersList.Player value) {
        if (playerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerIsMutable();
          player_.add(value);
          onChanged();
        } else {
          playerBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public Builder addPlayer(
          int index, protblog.PlayerOuterClass.PlayersList.Player value) {
        if (playerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerIsMutable();
          player_.add(index, value);
          onChanged();
        } else {
          playerBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public Builder addPlayer(
          protblog.PlayerOuterClass.PlayersList.Player.Builder builderForValue) {
        if (playerBuilder_ == null) {
          ensurePlayerIsMutable();
          player_.add(builderForValue.build());
          onChanged();
        } else {
          playerBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public Builder addPlayer(
          int index, protblog.PlayerOuterClass.PlayersList.Player.Builder builderForValue) {
        if (playerBuilder_ == null) {
          ensurePlayerIsMutable();
          player_.add(index, builderForValue.build());
          onChanged();
        } else {
          playerBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public Builder addAllPlayer(
          java.lang.Iterable<? extends protblog.PlayerOuterClass.PlayersList.Player> values) {
        if (playerBuilder_ == null) {
          ensurePlayerIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, player_);
          onChanged();
        } else {
          playerBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public Builder clearPlayer() {
        if (playerBuilder_ == null) {
          player_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          playerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public Builder removePlayer(int index) {
        if (playerBuilder_ == null) {
          ensurePlayerIsMutable();
          player_.remove(index);
          onChanged();
        } else {
          playerBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public protblog.PlayerOuterClass.PlayersList.Player.Builder getPlayerBuilder(
          int index) {
        return getPlayerFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public protblog.PlayerOuterClass.PlayersList.PlayerOrBuilder getPlayerOrBuilder(
          int index) {
        if (playerBuilder_ == null) {
          return player_.get(index);  } else {
          return playerBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public java.util.List<? extends protblog.PlayerOuterClass.PlayersList.PlayerOrBuilder> 
           getPlayerOrBuilderList() {
        if (playerBuilder_ != null) {
          return playerBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(player_);
        }
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public protblog.PlayerOuterClass.PlayersList.Player.Builder addPlayerBuilder() {
        return getPlayerFieldBuilder().addBuilder(
            protblog.PlayerOuterClass.PlayersList.Player.getDefaultInstance());
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public protblog.PlayerOuterClass.PlayersList.Player.Builder addPlayerBuilder(
          int index) {
        return getPlayerFieldBuilder().addBuilder(
            index, protblog.PlayerOuterClass.PlayersList.Player.getDefaultInstance());
      }
      /**
       * <code>repeated .protblog.PlayersList.Player player = 1;</code>
       */
      public java.util.List<protblog.PlayerOuterClass.PlayersList.Player.Builder> 
           getPlayerBuilderList() {
        return getPlayerFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protblog.PlayerOuterClass.PlayersList.Player, protblog.PlayerOuterClass.PlayersList.Player.Builder, protblog.PlayerOuterClass.PlayersList.PlayerOrBuilder> 
          getPlayerFieldBuilder() {
        if (playerBuilder_ == null) {
          playerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protblog.PlayerOuterClass.PlayersList.Player, protblog.PlayerOuterClass.PlayersList.Player.Builder, protblog.PlayerOuterClass.PlayersList.PlayerOrBuilder>(
                  player_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          player_ = null;
        }
        return playerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protblog.PlayersList)
    }

    // @@protoc_insertion_point(class_scope:protblog.PlayersList)
    private static final protblog.PlayerOuterClass.PlayersList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protblog.PlayerOuterClass.PlayersList();
    }

    public static protblog.PlayerOuterClass.PlayersList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PlayersList>
        PARSER = new com.google.protobuf.AbstractParser<PlayersList>() {
      @java.lang.Override
      public PlayersList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlayersList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayersList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protblog.PlayerOuterClass.PlayersList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protblog_PlayersList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protblog_PlayersList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protblog_PlayersList_Player_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protblog_PlayersList_Player_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014player.proto\022\010protblog\"\247\001\n\013PlayersList" +
      "\022,\n\006player\030\001 \003(\0132\034.protblog.PlayersList." +
      "Player\032j\n\006Player\022\020\n\010nickname\030\001 \002(\t\022\r\n\005em" +
      "ail\030\002 \002(\t\022\025\n\rdate_of_birth\030\003 \002(\t\022\n\n\002xp\030\004" +
      " \002(\005\022\034\n\003cls\030\005 \002(\0162\017.protblog.Class*5\n\005Cl" +
      "ass\022\013\n\007Berserk\020\000\022\010\n\004Tank\020\001\022\013\n\007Paladin\020\003\022" +
      "\010\n\004Mage\020\004"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protblog_PlayersList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protblog_PlayersList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protblog_PlayersList_descriptor,
        new java.lang.String[] { "Player", });
    internal_static_protblog_PlayersList_Player_descriptor =
      internal_static_protblog_PlayersList_descriptor.getNestedTypes().get(0);
    internal_static_protblog_PlayersList_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protblog_PlayersList_Player_descriptor,
        new java.lang.String[] { "Nickname", "Email", "DateOfBirth", "Xp", "Cls", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
